Homework 29
Otus-DevOps-2017-11/reddare_microservices pull request #12
Opened 2018-03-25 09:20 UTC by reddare

Добавлено домашнее задание 29.

2018-04-05 16:17 UTC, vitkhab requested changes
По факту сейчас приложение не работает. Принимать такую работу, даже если все сделано по инструкции, в моем понимании, - способствовать созданию вредной привычки.

Я вижу два варианта заставить приложение работать:
- собрать докер образа приложения без зипкина и проставив им соответствующий тег (или наоборот, образам с зипкином проставить тег), и в деплойментах явно указывать какой образ брать
- поднять в том же namespace'е zipkin, в этом случае будь аккуратен с тем, как ты задал в образе post переменную ZIPKIN_PORT.

В остальном все классно. Если бы не зипкин все бы работало.
Для сдачи ДЗ прошу тебя добиться работоспособности приложения. Можно использовать один из двух предложенных выше вариантов, можно придумать свое решение.

2018-04-11 10:54 UTC, reddare commented
Собрал приложение без зипкина, новый адрес приложения здесь: http://35.188.41.250:30040/
Прошу проверить!

2018-04-14 09:26 UTC, reddare commented
К сожалению ссылка на приложение перестала быть доступной. В 31 домашке пришлось убить лишнее в кластере, что бы высвободить ресурсы.

2018-04-19 18:53 UTC, vitkhab approved these changes
Спасибо. Вижу, что пересобрал. У меня приложение завелось.

Можно мерджить!

2018-04-20 19:32 UTC, merged