Homework 21
Otus-DevOps-2017-11/reddare_microservices pull request #7
Opened 2018-03-05 19:23 UTC by reddare

Добавлено домашнее задание 21.

2018-03-07 21:07 UTC, Nklya requested changes
Добрый вечер.

Антон, в принципе почти все выглядит ок.
- Вот только где папка monitoring/prometheus?
- Где /docker/.env.example?
- И где ссылка на Docker hub с образами в ридми?

2018-03-07 21:07 UTC, Nklya commented on README.md
> +Добавлен мониторинг сервисов comment,post, ui спомощью blackbox экспортера.
Вот только зачем папки monitoring/blackbox_exporter и monitoring/mongodb_exporter добавлены сабмодулями?

2018-03-09 18:53 UTC, reddare commented on README.md
> +Добавлен мониторинг сервисов comment,post, ui спомощью blackbox экспортера.
Поправил все что требовалось. Прошу повтороно проверить. Спасибо!

2018-03-09 21:43 UTC, Nklya approved these changes
Да, теперь все ок 👍

2018-03-09 21:43 UTC, Nklya commented on monitoring/blackbox_exporter/Dockerfile
> +FROM        quay.io/prometheus/busybox:latest
Блекбокс есть готовый образ, можно было прямо его использовать.

2018-03-09 21:43 UTC, Nklya commented on monitoring/mongodb_exporter/Dockerfile
> +FROM       golang:alpine as builder
Кстати, у перконы есть вроде бы более актуальный форк
https://github.com/percona/mongodb_exporter

2018-03-10 08:22 UTC, merged